services:
  - type: web
    name: ecosure-sitio-oficial
    runtime: static
    repo: https://github.com/qualmx1-lab/ecosure-sitio-oficial
    branch: main
    staticPublishPath: .
    pullRequestPreviewsEnabled: false
